#!/bin/bash

cp -a $DEPS/gcc .
cd gcc

# Not sure if this is needed at all. it fails anyways.
patch -Np1 -i ${PATCHDIR}/gcc/gcc-4.7.3-musl-1.patch

# GCC built-in prerequisites
cp -a $DEPS/gmp .
cp -a $DEPS/mpc .
cp -a $DEPS/mpfr .


#sed -i '/k prot/agcc_cv_libc_provides_ssp=yes' gcc/configure
#sed -i 's/if \((code.*))\)/if (\1 \&\& \!DEBUG_INSN_P (insn))/' gcc/sched-deps.c
#
## Avoid specific Glibc code
#( 
#cd libstdc++-v3/config/os
#mv gnu-linux gnu-linux.orig
#cp -r generic gnu-linux
#cp gnu-linux.orig/arm-eabi-extra.ver gnu-linux
#)
#
#sed -i 's/BUILD_INFO=info/BUILD_INFO=/' gcc/configure
#
rm -rf ../gcc-build
mkdir ../gcc-build
cd ../gcc-build

../gcc/configure \
  --prefix="$BUILDROOT/cross-tools" \
  --build=$HOST    \
  --host=$HOST    \
  --target=$TARGET \
  --with-sysroot="$BUILDROOT/cross-tools/$TARGET" \
  --with-newlib \
  --without-headers \
  --without-ppl \
  --without-cloog \
  --disable-nls  \
  --disable-shared \
  --disable-multilib \
  --disable-decimal-float \
  --disable-libgomp \
  --disable-libmudflap \
  --disable-libssp \
  --disable-libatomic \
  --disable-libquadmath \
  --disable-libitm \
  --disable-libvtv \
  --disable-libcilkrts \
  --disable-libstdc++-v3 \
  --disable-libstdcxx \
  --disable-libsanitizer \
  --disable-threads \
  --enable-languages=c \
  --with-mpfr-include=$(pwd)/../gcc/mpfr/src \
  --with-mpfr-lib=$(pwd)/mpfr/src/.libs 

make $JOBS all-gcc all-target-libgcc
make install-gcc install-target-libgcc
